### PR TITLE
Port vmcs tests to catch

### PR DESCRIPTION
**Pull request by connojd**

### CODE REVIEW

**Comment by rianquinn** [comment]
@connojd Looks like you have some unused functions and Windows is mad

**Comment by connojd** [comment]
@rianquinn is there a way to relax the function use checks?  they're definitely being used...

**Comment by rianquinn** [comment]
I will have to take a look at it. Might just be an issue with how the code is compiled.

**Comment by rianquinn** [comment]
@connojd please resubmit

**Comment by connojd** [comment]
@rianquinn tidy is complaining about no-undefined linker

**Comment by rianquinn** [comment]
@connojd I have a PR that should fix that as I was seeing something similar. While your waiting for that PR, there are some Codacy issues that still need to be fixed

**Comment by connojd** [comment]
@rianquinn it says there are no issues if you click on Details

**Comment by rianquinn** [comment]
Lol... yeah, I noticed that Codacy was complaining about functions not being used that are being used in other modules which is an obvious false positive, so I removed it so your good there.

**Pull request merged**
